/**
 * CSV Export Utility
 * Exports data to CSV format with proper formatting and metadata
 */

export interface ExportMetadata {
  title: string;
  exportDate: string;
  filters?: Record<string, any>;
  totalRecords: number;
  generatedBy?: string;
}

export interface ExportColumn {
  key: string;
  label: string;
  format?: (value: any) => string;
}

/**
 * Convert data to CSV format
 */
export function convertToCSV(
  data: any[],
  columns: ExportColumn[],
  metadata?: ExportMetadata
): string {
  const lines: string[] = [];

  // Add metadata as comments (if provided)
  if (metadata) {
    lines.push(`# ${metadata.title}`);
    lines.push(`# Export Date: ${metadata.exportDate}`);
    lines.push(`# Total Records: ${metadata.totalRecords}`);

    if (metadata.filters && Object.keys(metadata.filters).length > 0) {
      lines.push(`# Filters Applied: ${JSON.stringify(metadata.filters)}`);
    }

    if (metadata.generatedBy) {
      lines.push(`# Generated By: ${metadata.generatedBy}`);
    }

    lines.push(''); // Empty line after metadata
  }

  // Add header row
  const headers = columns.map(col => escapeCSV(col.label));
  lines.push(headers.join(','));

  // Add data rows
  data.forEach(row => {
    const values = columns.map(col => {
      const value = row[col.key];
      const formattedValue = col.format ? col.format(value) : value;
      return escapeCSV(formattedValue);
    });
    lines.push(values.join(','));
  });

  return lines.join('\n');
}

/**
 * Escape CSV value (handle commas, quotes, newlines)
 */
function escapeCSV(value: any): string {
  if (value === null || value === undefined) {
    return '';
  }

  const stringValue = String(value);

  // If value contains comma, quote, or newline, wrap in quotes and escape internal quotes
  if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
    return `"${stringValue.replace(/"/g, '""')}"`;
  }

  return stringValue;
}

/**
 * Download CSV file
 */
export function downloadCSV(
  csvContent: string,
  filename: string
): void {
  // Add BOM for proper Excel UTF-8 support
  const BOM = '\uFEFF';
  const blob = new Blob([BOM + csvContent], { type: 'text/csv;charset=utf-8;' });

  // Create download link
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up
  URL.revokeObjectURL(url);
}

/**
 * Format date for CSV
 */
export function formatDateForCSV(date: Date | number | string): string {
  const d = new Date(date);
  return d.toISOString();
}

/**
 * Format currency for CSV
 */
export function formatCurrencyForCSV(value: number, decimals: number = 2): string {
  return value.toFixed(decimals);
}

/**
 * Format percentage for CSV
 */
export function formatPercentageForCSV(value: number, decimals: number = 2): string {
  return `${value.toFixed(decimals)}%`;
}

/**
 * Generate filename with timestamp
 */
export function generateFilename(prefix: string, extension: string = 'csv'): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  return `${prefix}_${timestamp}.${extension}`;
}

/**
 * Export portfolio data to CSV
 */
export function exportPortfolioToCSV(holdings: any[]): void {
  const columns: ExportColumn[] = [
    { key: 'asset', label: 'Asset' },
    { key: 'assetType', label: 'Type' },
    { key: 'quantity', label: 'Quantity', format: (v) => formatCurrencyForCSV(v, 8) },
    { key: 'acquiredPrice', label: 'Acquired Price ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'currentPrice', label: 'Current Price ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'totalValue', label: 'Total Value ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'unrealizedPnL', label: 'Unrealized P&L ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'unrealizedPnLPercentage', label: 'Unrealized P&L (%)', format: (v) => formatPercentageForCSV(v) },
    { key: 'acquiredDate', label: 'Acquired Date', format: formatDateForCSV },
  ];

  const metadata: ExportMetadata = {
    title: 'CYPHER V3 - Portfolio Holdings',
    exportDate: new Date().toISOString(),
    totalRecords: holdings.length,
    generatedBy: 'CYPHER V3 Platform',
  };

  const csv = convertToCSV(holdings, columns, metadata);
  const filename = generateFilename('portfolio_holdings');
  downloadCSV(csv, filename);
}

/**
 * Export transactions to CSV
 */
export function exportTransactionsToCSV(transactions: any[]): void {
  const columns: ExportColumn[] = [
    { key: 'id', label: 'Transaction ID' },
    { key: 'type', label: 'Type' },
    { key: 'asset', label: 'Asset' },
    { key: 'assetType', label: 'Asset Type' },
    { key: 'amount', label: 'Amount', format: (v) => formatCurrencyForCSV(v, 8) },
    { key: 'price', label: 'Price ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'value', label: 'Value ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'fee', label: 'Fee ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'txHash', label: 'Transaction Hash' },
    { key: 'status', label: 'Status' },
    { key: 'timestamp', label: 'Date', format: formatDateForCSV },
  ];

  const metadata: ExportMetadata = {
    title: 'CYPHER V3 - Transaction History',
    exportDate: new Date().toISOString(),
    totalRecords: transactions.length,
    generatedBy: 'CYPHER V3 Platform',
  };

  const csv = convertToCSV(transactions, columns, metadata);
  const filename = generateFilename('transaction_history');
  downloadCSV(csv, filename);
}

/**
 * Export market data to CSV
 */
export function exportMarketDataToCSV(marketData: any[]): void {
  const columns: ExportColumn[] = [
    { key: 'symbol', label: 'Symbol' },
    { key: 'name', label: 'Name' },
    { key: 'price', label: 'Price ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'change24h', label: '24h Change (%)', format: (v) => formatPercentageForCSV(v) },
    { key: 'volume24h', label: '24h Volume ($)', format: (v) => formatCurrencyForCSV(v, 0) },
    { key: 'marketCap', label: 'Market Cap ($)', format: (v) => formatCurrencyForCSV(v, 0) },
    { key: 'high24h', label: '24h High ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'low24h', label: '24h Low ($)', format: (v) => formatCurrencyForCSV(v) },
  ];

  const metadata: ExportMetadata = {
    title: 'CYPHER V3 - Market Data',
    exportDate: new Date().toISOString(),
    totalRecords: marketData.length,
    generatedBy: 'CYPHER V3 Platform',
  };

  const csv = convertToCSV(marketData, columns, metadata);
  const filename = generateFilename('market_data');
  downloadCSV(csv, filename);
}

/**
 * Export historical price data to CSV
 */
export function exportHistoricalDataToCSV(historicalData: any[], symbol: string): void {
  const columns: ExportColumn[] = [
    { key: 'timestamp', label: 'Timestamp', format: formatDateForCSV },
    { key: 'open', label: 'Open ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'high', label: 'High ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'low', label: 'Low ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'close', label: 'Close ($)', format: (v) => formatCurrencyForCSV(v) },
    { key: 'volume', label: 'Volume', format: (v) => formatCurrencyForCSV(v, 0) },
  ];

  const metadata: ExportMetadata = {
    title: `CYPHER V3 - Historical Price Data (${symbol})`,
    exportDate: new Date().toISOString(),
    totalRecords: historicalData.length,
    generatedBy: 'CYPHER V3 Platform',
  };

  const csv = convertToCSV(historicalData, columns, metadata);
  const filename = generateFilename(`historical_${symbol.toLowerCase()}`);
  downloadCSV(csv, filename);
}

/**
 * Export whale tracker data to CSV
 */
export function exportWhaleDataToCSV(whaleData: any[]): void {
  const columns: ExportColumn[] = [
    { key: 'timestamp', label: 'Timestamp', format: formatDateForCSV },
    { key: 'address', label: 'Address' },
    { key: 'type', label: 'Type' },
    { key: 'asset', label: 'Asset' },
    { key: 'amount', label: 'Amount', format: (v) => formatCurrencyForCSV(v, 8) },
    { key: 'valueUSD', label: 'Value (USD)', format: (v) => formatCurrencyForCSV(v, 0) },
    { key: 'txHash', label: 'Transaction Hash' },
  ];

  const metadata: ExportMetadata = {
    title: 'CYPHER V3 - Whale Tracker Data',
    exportDate: new Date().toISOString(),
    totalRecords: whaleData.length,
    generatedBy: 'CYPHER V3 Platform',
  };

  const csv = convertToCSV(whaleData, columns, metadata);
  const filename = generateFilename('whale_tracker');
  downloadCSV(csv, filename);
}

/**
 * Export holder analytics to CSV
 */
export function exportHolderDataToCSV(holderData: any[]): void {
  const columns: ExportColumn[] = [
    { key: 'address', label: 'Address' },
    { key: 'balance', label: 'Balance', format: (v) => formatCurrencyForCSV(v, 8) },
    { key: 'percentage', label: 'Percentage (%)', format: (v) => formatPercentageForCSV(v) },
    { key: 'rank', label: 'Rank' },
    { key: 'firstSeen', label: 'First Seen', format: formatDateForCSV },
    { key: 'lastActivity', label: 'Last Activity', format: formatDateForCSV },
  ];

  const metadata: ExportMetadata = {
    title: 'CYPHER V3 - Holder Analytics',
    exportDate: new Date().toISOString(),
    totalRecords: holderData.length,
    generatedBy: 'CYPHER V3 Platform',
  };

  const csv = convertToCSV(holderData, columns, metadata);
  const filename = generateFilename('holder_analytics');
  downloadCSV(csv, filename);
}

/**
 * Generic export function for custom data
 */
export function exportGenericDataToCSV(
  data: any[],
  columns: ExportColumn[],
  title: string,
  filenamePrefix: string
): void {
  const metadata: ExportMetadata = {
    title: `CYPHER V3 - ${title}`,
    exportDate: new Date().toISOString(),
    totalRecords: data.length,
    generatedBy: 'CYPHER V3 Platform',
  };

  const csv = convertToCSV(data, columns, metadata);
  const filename = generateFilename(filenamePrefix);
  downloadCSV(csv, filename);
}
